# This file was generated by GoReleaser. DO NOT EDIT.
class P < Formula
  desc "P is a cli for Potantially."
  homepage ""
  url "http://potentially-p-releases.s3.eu-west-1.amazonaws.com/v0.0.16/p_0.0.16_darwin_amd64.zip"
  version "0.0.16"
  sha256 "77783dfdab6548ab830be1e9cb51514bebc1e080dcdc556db6126a9149aa766b"

  def install
    bin.install "p"
  end
end
