# This file was generated by GoReleaser. DO NOT EDIT.
class P < Formula
  desc "P is a cli for Potantially."
  homepage ""
  version "0.0.27"
  bottle :unneeded

  if OS.mac?
    url "http://potentially-p-releases.s3.eu-west-1.amazonaws.com/0.0.27/p_0.0.27_darwin_amd64.zip"
    sha256 "570b82ef16d469bf57689579a5f215d2d8cdf989b776c1d1f16c4870e6240c1e"
  elsif OS.linux?
  end

  def install
    bin.install "p"
  end
end
