# This file was generated by GoReleaser. DO NOT EDIT.
class P < Formula
  desc "P is a cli for Potantially."
  homepage ""
  url "http://potentially-p-releases.s3.eu-west-1.amazonaws.com/v0.0.20/p_0.0.20_darwin_amd64.zip"
  version "0.0.20"
  sha256 "a8fdcfb713e820ff6807814fb6db6e6caeccf69739c1655f821cca0d2802b570"

  def install
    bin.install "p"
  end
end
